services:
  - type: web
    name: Portfolio
    env: docker
    region: virginia
    branch: main
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        value: ""
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        value: ""
      - key: CORS_ALLOWED_ORIGINS
        value: ""
